env:
  es6: true
  node: true
  jest/globals: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:promise/recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended
  - plugin:jest/style

parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json

plugins:
  - jest
  - simple-import-sort
  - prettier

rules:
  import/default: off
  import/order: off
  simple-import-sort/imports: error
  require-await: off
  "@typescript-eslint/no-unsafe-assignment": warn
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/require-await": error
  "jest/no-done-callback": off

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
