repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]

  - repo: https://github.com/aws-samples/automated-security-helper
    rev: '1.0.9-e-16May2023' # update with the latest-tagged version in the repository
    hooks:
      - id: ash
        stages: [ manual ]
        # uncomment the line below if using "finch" on MacOS
        # args: [ "-f" ]

  - repo: https://github.com/sbrunner/pre-commit-copyright
    rev: 0.7.0
    hooks:
      - id: copyright
        name: update copyright
        exclude: |
          (?x)^(
            ^\..+|
            .+\.md|
            jest.config.js|
            LICENSE|
            package.json|
            package-lock.json
            tsconfig.json|
          )$
      - id: copyright-required
        name: require copyright
        exclude: |
          (?x)^(
            ^\..+|
            .+\.md|
            jest.config.js|
            LICENSE|
            package.json|
            package-lock.json|
            tsconfig.json|
          )$
