name: build

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build Package
        run: |
          npm ci
          npm run build --if-present
      - name: Install Pre-commit
        run: |
          pip install pre-commit
      - name: Run Pre-commit for Changed Files
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD | xargs pre-commit run --files
      - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          annotations: failed-tests
