name: build

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build Package
        run: |
          npm ci
          npm run build --if-present
      - uses: pre-commit/action@v3.0.0
      - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          annotations: failed-tests
