name: Build CDK Constructs NPM

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
      - uses: pre-commit/action@v3.0.0
      - name: Jest coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.0
