name: "OSML CDK Constructs Build Workflow"

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  Build_NPM:
    uses: ./.github/workflows/npm-build.yml
    secrets: inherit
  Publish_Documentation:
    needs: [Build_NPM]
    uses: ./.github/workflows/documentation-publish.yml
    secrets: inherit
