name: publish

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish Package on NPM
        run: |
          npm ci
          npm run build
          npm publish -access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
