name: release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish:
    needs: [build]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
  docs:
    needs: [publish]
    uses: ./.github/workflows/docs.yml
    secrets: inherit
